name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  phpstan:
    name: PHPStan Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run PHPStan
        run: composer phpstan

  phpunit:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read           # required for codecov/action
      pull-requests: write     # allow PR comments from Codecov
    strategy:
      matrix:
        php-version: ['8.3', '8.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: ${{ matrix.php-version == '8.3' && 'pcov' || 'none' }}
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run PHPUnit (no coverage)
        if: matrix.php-version != '8.3'
        run: composer test

      - name: Run PHPUnit with coverage (Clover)
        if: matrix.php-version == '8.3'
        run: |
          ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage artifact (optional)
        if: matrix.php-version == '8.3'
        uses: actions/upload-artifact@v4
        with:
          name: clover-${{ matrix.php-version }}
          path: coverage.xml

      - name: Upload coverage to Codecov
        if: matrix.php-version == '8.3'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: php,phpunit
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
